### ISSUE TITLE
Don't crash on JSONDecodeError

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/tbs#23]
I tried to run TBS locally today and got this error:
```
Fetching issues for releng
Fetching issues for fedora-infrastructure
Fetching issues for koji-fedmsg-plugin
Traceback (most recent call last):
  File "tbs.py", line 274, in <module>
    main()
  File "tbs.py", line 229, in main
    gather_pagure_tickets(project, all_tickets, state)
  File "tbs.py", line 93, in gather_pagure_tickets
    jsonobj = requests.get(url).json()
  File "/var/home/zlopez/git/tbs/.venv/lib64/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

We shouldn't crash on this error, but what should we do?
Skip the project and try it again in next iteration?

**Comment by 0xamrzaky** [comment]
it's working normally and fetch koji-fedmsg-plugin tickets successfully

**Comment by Zlopez** [comment]
@amrmostafazaki It's only happens sometimes

**Comment by 0xamrzaky** [comment]
@Zlopez ha okay, let me catch it
